journal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'), # home page
    path('logs/', views.log_list, name='log'), # log page
    path('log/<int:log_id>/', views.log_detail, name='log_detail'),
    path('new_log/', views.new_log, name='new_log'),
    path('new_entry/<int:log_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry')
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('journal.urls')),
    path('users/', include('users.urls'))
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('sign_up/', views.sign_up, name='sign_up')
]

journal/models.py
from tabnanny import verbose
from django.db import models

# Create your models here.

class Log(models.Model):
    content = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content

class Entry(models.Model):
    log = models.ForeignKey(Log, on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.content 

users/models.py
from django.db import models

# Create your models here.

journal/forms.py
from django import forms 
from .models import Log, Entry

class LogForm(forms.ModelForm):
    class Meta:
        model = Log
        fields = ['content']
        labels = {'content': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['content']
        labels = {'content': 'Entry'}
        widgets = {'content': forms.Textarea(attrs={'cols': 80})}

journal/views.py
from django.shortcuts import render, redirect
from .models import Entry, Log
from .forms import LogForm, EntryForm

# Create your views here.

def home(req):
    return render(req, 'journal/home.html')

def log_list(req):
    logs = Log.objects.order_by('date_added')
    context = {'logs': logs}

    return render(req, 'journal/log.html', context)

def log_detail(req, log_id):
    log = Log.objects.get(id=log_id)
    entries = Entry.objects.filter(log=log)
    context = {'log': log, 'entries': entries}

    return render(req, 'journal/log_detail.html', context)

def new_log(req):
    if req.method != 'POST':
        form = LogForm()
    else:
        form = LogForm(data=req.POST)
        if form.is_valid():
            form.save()
            return redirect('log')

    context = { 'form': form}
    return render(req, 'journal/new_log.html', context)

def new_entry(req, log_id):
    log = Log.objects.get(id=log_id)

    if req.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=req.data)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.log = log
            new_entry.save()

            return redirect('log_detail', log_id=log_id)
    
    context = {'log': log, 'form': form}
    return render(req, 'journal/new_entry.html', context)

def edit_entry(req, entry_id):
    entry = Entry.objects.get(id=entry_id)
    log = entry.log 

    if req.method != "POST":
        form = EntryForm(instance=entry)

    else:
        form = EntryForm(instance=entry, data=req.POST)
        if form.is_valid():
            form.save() 
            return redirect('log_detail', log_id=log.id)
        
    context = {'entry': entry, 'log': log, 'form': form}
    return render(req, 'journal/edit_entry.html', context)
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def sign_up(req):
    if req.method != "POST":
        form = UserCreationForm() 

    else: 
        form = UserCreationForm(data=req.POST)

        if form.is_valid():
            new_user = form.save()

            login(req, new_user)
            return redirect('home')

    context = {'form': form }
    return render(req, 'registration/sign_up.html', context)

journal/templates/journal/base.html
<p>
    <a href={% url 'home' %}>Journal</a>
    <a href={% url 'log' %}>Log</a>
    {% if user.is_authenticated %}
        Welcome, {{ user.username }}
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else%}
        <a href={% url 'users:sign_up' %}>Sign up</a>
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>

{% block content%}{% endblock content %}

journal/templates/journal/edit_entry.html
{% extends "journal/base.html" %}

{% block content %}
    <p><a href="{% url 'log_detail' log.id %}">{{log}}</a></p>

    <p>Edit entry:</p>

    <form action="{% url 'edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p}}

        <button name="Submmit">Save changes</button>

    </form>

{% endblock content %}

journal/templates/journal/home.html
{% extends "journal/base.html" %}

{% block content %}
    <p>Safe place to express</p>
{% endblock content %}

journal/templates/journal/log.html
{% extends "journal/base.html" %}

{% block content %}
    <p>Log</p>

    <ul>
        {% for log in logs %}
            <li><a href="{% url 'log_detail' log.id %}">{{ log }}</a></li>
            
        {% empty %}
            <li>No log yet.</li>
        {% endfor %}
    </ul>

    <a href="{% url 'new_log' %}">Add a new log</a>

{% endblock content %}

journal/templates/journal/log_detail.html
{% extends 'journal/base.html' %}

{% block content %}

    <p>Log: {{log}}</p>
    <p>Entries</p>
    <p>
        <a href="{% url 'new_entry' log.id %}">Add new entry</a>
    </p> 
    <ul>
        {% for entry in entries %}
            <li>
                <p>{{ entry.date_updated }}</p>
                <p>{{ entry.content | linebreaks}}</p>
                <p>
                    <a href="{% url 'edit_entry' entry.id %}">Edit entry</a>
                </p>
            </li>
            {% empty %}
                <li>There are np entries for this Log</li>

        {% endfor %}
    </ul>

{% endblock content %}

journal/templates/journal/new_entry.html
{% extends "journal/base.html" %}

{% block content %}
    <p><a href="{% url 'log_detail' log.id %}"}>{{ log }}</a></p>

    <p>Add a new entry</p>
    <form action="{% url 'new_entry' log.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add entry</button>
 
    </form>
{% endblock content %}

journal/templates/journal/new_log.html
{% extends "journal/base.html" %}

{% block content %}
    <p>Add a new topic:</p>

    <form action="{% url 'new_log' %}" method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='sbumit'>Add log</button>
    </form>

{% endblock content %}